import { COMPARE_TYPES } from "../../../../../core/functions/conditions";

export const sessionRecordingsAttributes = [
  {
    type: "text",
    placeholder: "File Name",
    name: "originalFileName",
    validation: "",
    default: "",
    label: "File Name",
    tag: true,
    view: true,
    add: false,
    update: false,
  },
  {
    type: "select",
    apiType: "API",
    selectApi: "session/select",
    placeholder: "Session",
    name: "session",
    validation: "",
    showItem: "title",
    default: "",
    tag: true,
    label: "Session",
    required: true,
    view: true,
    add: false,
    update: false,
    filter: false,
  },
  {
    type: "hidden",
    apiType: "JSON",
    selectApi: "pending,converted,processed,failed",
    placeholder: "Processing Status",
    name: "status",
    collection: "processingProgress",
    validation: "",
    default: "pending",
    label: "Processing Status",
    required: false,
    tag: true,
    view: false,
    add: false,
    update: false,
  },
  {
    type: "hidden",
    placeholder: "Status",
    name: "status",
    validation: "",
    default: "",
    tag: true,
    label: "Status",
    required: true,
    view: true,
    add: false,
    update: false,
    hide: true,
    statusLabel: {
      nextLine: false,
      size: "small",
      conditions: [
        {
          when: "status",
          condition: COMPARE_TYPES.EQUALS,
          compare: "pending",
          type: "text",
          label: "Pending",
          icon: "pending",
          color: "beige",
        },
        {
          when: "status",
          condition: COMPARE_TYPES.EQUALS,
          compare: "converted",
          type: "text",
          label: "Uploaded",
          icon: "upload",
          color: "mage",
        },
        {
          when: "status",
          condition: COMPARE_TYPES.EQUALS,
          compare: "processed",
          type: "text",
          label: "Processed",
          icon: "tick",
          color: "mint",
        },
        {
          when: "status",
          condition: COMPARE_TYPES.EQUALS,
          compare: "failed",
          type: "text",
          label: "Failed",
          icon: "close",
          color: "red",
        },
      ],
    },
  },
];
