// Notification Queue Attributes Configuration
// This file contains the form field definitions for the notification queue management

export const notificationQueueAttributes = [
  {
    type: "title",
    title: "Basic Information",
    name: "basicInfo",
    add: true,
    update: true,
  },
  {
    type: "select",
    apiType: "API",
    selectApi: "ticket-registration/select",
    placeholder: "Select ticket registration",
    name: "ticketRegistrationId",
    showItem: "name",
    label: "Ticket Registration",
    required: true,
    tag: true,
    view: true,
    add: true,
    update: true,
    filter: true,
    icon: "ticket",
    customClass: "full",
  },
  {
    type: "text",
    placeholder: "First Name",
    name: "firstName",
    label: "First Name",
    required: false,
    view: true,
    add: false,
    tag: true,
    update: false,
    filter: true,
    icon: "user",
    customClass: "half",
    // Use collection and showItem to extract firstName from nested structure
    collection: "ticketRegistrationId",
    showItem: "value.firstName",
    showSubItem: "firstName",
  },
  {
    type: "select",
    apiType: "CSV",
    selectApi: "send,resend,approval,bulk_resend",
    placeholder: "Select notification type",
    name: "notificationType",
    showItem: "notificationType",
    label: "Notification Type",
    required: true,
    tag: true,
    view: true,
    add: true,
    update: true,
    filter: true,
    icon: "notification",
    customClass: "half",
  },
  {
    type: "select",
    apiType: "API",
    selectApi: "event/select",
    placeholder: "Select event",
    name: "eventId",
    showItem: "name",
    label: "Event",
    required: true,
    tag: true,
    view: true,
    add: true,
    update: true,
    filter: true,
    icon: "event",
    customClass: "half",
  },
  {
    type: "select",
    apiType: "CSV",
    selectApi: "pending,processing,completed,failed",
    placeholder: "Select status",
    name: "status",
    showItem: "status",
    label: "Status",
    required: true,
    tag: true,
    view: true,
    add: true,
    update: true,
    filter: true,
    icon: "status",
    customClass: "half",
  },
  {
    type: "line",
    add: true,
    update: true,
  },
  {
    type: "title",
    title: "Channel Settings",
    name: "channelInfo",
    add: true,
    update: true,
  },
  {
    type: "toggle",
    name: "channels.email.enabled",
    label: "Enable Email Notification",
    required: false,
    view: true,
    add: true,
    update: true,
    default: false,
    customClass: "half",
  },
  {
    type: "select",
    apiType: "CSV",
    selectApi: "pending,processing,sent,failed,skipped",
    placeholder: "Select email status",
    name: "channels.email.status",
    showItem: "status",
    label: "Email Status",
    required: false,
    view: true,
    add: false,
    update: true,
    icon: "email",
    customClass: "half",
  },
  {
    type: "toggle",
    name: "channels.whatsapp.enabled",
    label: "Enable WhatsApp Notification",
    required: false,
    view: true,
    add: true,
    update: true,
    default: false,
    customClass: "half",
  },
  {
    type: "select",
    apiType: "CSV",
    selectApi: "pending,processing,sent,failed,skipped",
    placeholder: "Select WhatsApp status",
    name: "channels.whatsapp.status",
    showItem: "status",
    label: "WhatsApp Status",
    required: false,
    view: true,
    add: false,
    update: true,
    icon: "whatsapp",
    customClass: "half",
  },
  {
    type: "line",
    add: true,
    update: true,
  },
  {
    type: "title",
    title: "SMS Settings",
    name: "smsInfo",
    add: true,
    update: true,
  },
  {
    type: "toggle",
    name: "channels.sms.enabled",
    label: "Enable SMS Notification",
    required: false,
    view: true,
    add: true,
    update: true,
    default: false,
    customClass: "half",
  },
  {
    type: "select",
    apiType: "CSV",
    selectApi: "pending,processing,sent,failed,skipped",
    placeholder: "Select SMS status",
    name: "channels.sms.status",
    showItem: "status",
    label: "SMS Status",
    required: false,
    view: true,
    add: false,
    update: true,
    icon: "sms",
    customClass: "half",
  },
  {
    type: "line",
    add: true,
    update: true,
  },
  {
    type: "title",
    title: "Timing Information",
    name: "timingInfo",
    add: true,
    update: true,
  },
  {
    type: "datetime",
    split: true,
    placeholder: "Select scheduled time",
    name: "scheduledAt",
    label: "Scheduled At",
    required: false,
    view: true,
    add: true,
    update: true,
    icon: "time",
    customClass: "half",
  },
  {
    type: "datetime",
    split: true,
    placeholder: "Select processed time",
    name: "processedAt",
    label: "Processed At",
    required: false,
    view: true,
    add: false,
    update: true,
    icon: "time",
    customClass: "half",
  },
  {
    type: "line",
    add: true,
    update: true,
  },
  {
    type: "title",
    title: "Additional Information",
    name: "additionalInfo",
    add: true,
    update: true,
  },
  {
    type: "textarea",
    placeholder: "Enter error message if any...",
    name: "errorMessage",
    label: "Error Message",
    required: false,
    view: true,
    add: false,
    update: true,
    rows: 3,
    customClass: "full",
  },
  {
    type: "textarea",
    placeholder: "Enter retry information...",
    name: "retryInfo",
    label: "Retry Information",
    required: false,
    view: true,
    add: false,
    update: true,
    rows: 3,
    customClass: "full",
  },
  {
    type: "number",
    placeholder: "Enter retry count",
    name: "retryCount",
    label: "Retry Count",
    required: false,
    view: true,
    add: false,
    update: true,
    min: 0,
    max: 10,
    step: 1,
    customClass: "half",
  },
  {
    type: "number",
    placeholder: "Enter priority",
    name: "priority",
    label: "Priority",
    required: false,
    view: true,
    add: true,
    update: true,
    min: 1,
    max: 10,
    step: 1,
    default: 5,
    customClass: "half",
  },
  {
    type: "line",
    add: true,
    update: true,
  },
  {
    type: "title",
    title: "Metadata",
    name: "metadataInfo",
    add: true,
    update: true,
  },
  {
    type: "textarea",
    placeholder: "Enter metadata JSON...",
    name: "metadata",
    label: "Metadata",
    required: false,
    view: true,
    add: false,
    update: true,
    rows: 4,
    footnote: "Additional data in JSON format",
    customClass: "full",
  },
];
