import React from "react";
import { GetIcon } from "../../../../icons/index.jsx";

export const rubricAttributes = [
  // Section: Settings
  {
    type: "title",
    title: "Rubric Settings",
    add: true,
    update: true,
    subGroup: "rubric-settings",
    customClass: "full",
  },
  
  {
    type: "text",
    placeholder: "Rubric Name",
    name: "rubricName",
    validation: "",
    default: "",
    tag: true,
    label: "Rubric Name",
    required: true,
    view: true,
    add: true,
    update: true,
    subGroup: "rubric-settings",
    icon: "title",
    customClass: "full",
  },
  {
    type: "element",
    name: "weightDistribution",
    label: "Total Weight Distribution",
    view: true,
    add: true,
    update: true,
    subGroup: "rubric-settings",
    customClass: "full",
    element: ({ formValues, data, setFormValues, setMessage, referenceId, parents }) => {
      // Calculate total weight from all criteria
      // For now, calculate from formValues if available, otherwise show placeholder
      const calculateTotalWeight = () => {
        // If criteria are in formValues (when editing a rubric with multiple criteria)
        if (formValues && Array.isArray(formValues.criteria)) {
          return formValues.criteria.reduce((sum, criterion) => {
            const weight = parseFloat(criterion?.weight) || 0;
            return sum + weight;
          }, 0);
        }
        // If criteria are in data
        if (data && Array.isArray(data.criteria)) {
          return data.criteria.reduce((sum, criterion) => {
            const weight = parseFloat(criterion?.weight) || 0;
            return sum + weight;
          }, 0);
        }
        // Calculate from individual weight fields if they exist in formValues
        const weightFields = ['weight', 'methodologyWeight', 'clarityWeight', 'relevanceWeight', 'overallWeight'];
        return weightFields.reduce((sum, field) => {
          const weight = parseFloat(formValues?.[field]) || 0;
          return sum + weight;
        }, 0);
      };

      const totalWeight = calculateTotalWeight();
      const isComplete = Math.abs(totalWeight - 100) < 0.01; // Allow for floating point precision
      
      return (
        <div className="bg-bg-weak rounded-lg p-4 border border-stroke-soft">
          <div className="flex items-start justify-between">
            <div className="flex-1">
              <label className="text-sm font-medium text-text-main mb-1 block">Total Weight Distribution</label>
              <p className="text-xs text-text-sub mb-3">Should equal 100% (text fields excluded)</p>
            </div>
            <div className="text-right">
              <div className={`text-2xl font-bold ${isComplete ? "text-state-success" : "text-state-error"}`}>
                {totalWeight}%
              </div>
              {!isComplete && (
                <button
                  type="button"
                  onClick={() => {
                    if (setMessage) {
                      setMessage({
                        type: 1,
                        content: "Please adjust criterion weights to total 100%",
                        icon: "info",
                        title: "Adjust Weights",
                      });
                    }
                  }}
                  className="text-xs text-state-error hover:underline mt-1"
                >
                  Adjust weights
                </button>
              )}
            </div>
          </div>
          <div className="mt-4 pt-4 border-t border-stroke-soft">
            <button
              type="button"
              onClick={() => {
                if (setMessage) {
                  setMessage({
                    type: 1,
                    content: "Load from Template feature coming soon",
                    icon: "info",
                    title: "Load Template",
                  });
                }
              }}
              className="flex items-center gap-2 text-sm text-primary-base hover:text-primary-dark"
            >
              <GetIcon icon="document" />
              <span>Load from Template</span>
            </button>
          </div>
        </div>
      );
    },
  },

  // Section: Criterion
  {
    type: "title",
    title: "Evaluation Criteria (5)",
    add: true,
    update: true,
    subGroup: "evaluation-criteria",
    customClass: "full",
  },
  
  {
    type: "text",
    placeholder: "Criterion Title", 
    name: "title",
    validation: "",
    default: "",
    tag: true,
    label: "Criterion Title",
    required: true,
    view: true,
    add: true,
    update: true,
    group: "1. Originality & Innovation",
    customClass: "full",
  },
  {
    type: "textarea",
    placeholder: "Description (Instructions for Reviewers)",
    name: "description",
    label: "Description (Instructions for Reviewers)",
    required: false,
    view: true,
    add: true,
    update: true,
    group: "1. Originality & Innovation",
    customClass: "full",
  },
  {
    type: "select",
    name: "responseType",
    label: "Scale Rating",
    required: true,
    view: true,
    add: true,
    update: true,
    apiType: "JSON",
    selectApi: [
      { id: "1-5", value: "Scale Rating (1-5)" },
      { id: "1-10", value: "Scale Rating (1-10)" },
    ],
    customClass: "half",
    group: "1. Originality & Innovation",
  },
  {
    type: "number",
    placeholder: "Weight (%)",
    name: "weight",
    label: "Weight (%)",
    required: true,
    view: true,
    add: true,
    update: true,
    group: "1. Originality & Innovation",
    customClass: "quarter",
    tag: true,
  },
  {
    type: "checkbox",
    name: "required",
    label: "Required (reviewers must answer)",
    default: false,
    required: false,
    view: true,
    add: true,
    update: true,
    group: "1. Originality & Innovation",
    customClass: "quarter",
    tag: true,
  },
  {
    type: "number",
    placeholder: "Min Value",
    name: "minValue",
    label: "Min Value",
    required: true,
    view: true,
    add: true,
    update: true,
    group: "1. Originality & Innovation",
    customClass: "half",
  },
  {
    type: "number",
    placeholder: "Max Value",
    name: "maxValue",
    label: "Max Value",
    required: true,
    view: true,
    add: true,
    update: true,
    group: "1. Originality & Innovation",
    customClass: "half",
  },
  {
    type: "text",
    placeholder: "Min Label",
    name: "minLabel",
    label: "Min Label",
    required: false,
    view: true,
    add: true,
    update: true,
    group: "1. Originality & Innovation",
    customClass: "half",
  },
  {
    type: "text",
    placeholder: "Max Label",
    name: "maxLabel",
    label: "Max Label",
    required: false,
    view: true,
    add: true,
    update: true,
    group: "1. Originality & Innovation",
    customClass: "half",
  },
  // Section: 2. Research Methodologyy (same fields as 1. Originality & Innovation)
  
  {
    type: "text",
    placeholder: "Criterion Title",
    name: "methodologyTitle",
    validation: "",
    default: "",
    tag: true,
    label: "Criterion Title",
    required: true,
    view: true,
    add: true,
    update: true,
    group: "2. Research Methodologyy",
    customClass: "full",
  },
  {
    type: "textarea",
    placeholder: "Description (Instructions for Reviewers)",
    name: "methodologyDescription",
    label: "Description (Instructions for Reviewers)",
    required: false,
    view: true,
    add: true,
    update: true,
    group: "2. Research Methodologyy",
    customClass: "full",
  },
  {
    type: "select",
    name: "methodologyResponseType",
    label: "Scale Rating",
    required: true,
    view: true,
    add: true,
    update: true,
    apiType: "JSON",
    selectApi: [
      { id: "1-5", value: "Scale Rating (1-5)" },
      { id: "1-10", value: "Scale Rating (1-10)" },
    ],
    customClass: "half",
    group: "2. Research Methodologyy",
  },
  {
    type: "number",
    placeholder: "Weight (%)",
    name: "methodologyWeight",
    label: "Weight (%)",
    required: true,
    view: true,
    add: true,
    update: true,
    group: "2. Research Methodologyy",
    customClass: "quarter",
    tag: true,
  },
  {
    type: "checkbox",
    name: "methodologyRequired",
    label: "Required (reviewers must answer)",
    default: false,
    required: false,
    view: true,
    add: true,
    update: true,
    group: "2. Research Methodologyy",
    customClass: "quarter",
    tag: true,
  },
  {
    type: "number",
    placeholder: "Min Value",
    name: "methodologyMinValue",
    label: "Min Value",
    required: true,
    view: true,
    add: true,
    update: true,
    group: "2. Research Methodologyy",
    customClass: "half",
  },
  {
    type: "number",
    placeholder: "Max Value",
    name: "methodologyMaxValue",
    label: "Max Value",
    required: true,
    view: true,
    add: true,
    update: true,
    group: "2. Research Methodologyy",
    customClass: "half",
  },
  {
    type: "text",
    placeholder: "Min Label",
    name: "methodologyMinLabel",
    label: "Min Label",
    required: false,
    view: true,
    add: true,
    update: true,
    group: "2. Research Methodologyy",
    customClass: "half",
  },
  {
    type: "text",
    placeholder: "Max Label",
    name: "methodologyMaxLabel",
    label: "Max Label",
    required: false,
    view: true,
    add: true,
    update: true,
    group: "2. Research Methodologyy",
    customClass: "half",
  },
  // Section: 3. Clarity of Abstract
  {
    type: "text",
    placeholder: "Criterion Title",
    name: "clarityTitle",
    validation: "",
    default: "",
    tag: true,
    label: "Criterion Title",
    required: true,
    view: true,
    add: true,
    update: true,
    group: "3. Clarity of Abstract",
    customClass: "full",
  },
  {
    type: "textarea",
    placeholder: "Description (Instructions for Reviewers)",
    name: "clarityDescription",
    label: "Description (Instructions for Reviewers)",
    required: false,
    view: true,
    add: true,
    update: true,
    group: "3. Clarity of Abstract",
    customClass: "full",
  },
  {
    type: "select",
    name: "clarityResponseType",
    label: "Scale Rating",
    required: true,
    view: true,
    add: true,
    update: true,
    apiType: "JSON",
    selectApi: [
      { id: "1-5", value: "Scale Rating (1-5)" },
      { id: "1-10", value: "Scale Rating (1-10)" },
    ],
    customClass: "half",
    group: "3. Clarity of Abstract",
  },
  {
    type: "number",
    placeholder: "Weight (%)",
    name: "clarityWeight",
    label: "Weight (%)",
    required: true,
    view: true,
    add: true,
    update: true,
    group: "3. Clarity of Abstract",
    customClass: "quarter",
    tag: true,
  },
  {
    type: "checkbox",
    name: "clarityRequired",
    label: "Required (reviewers must answer)",
    default: false,
    required: false,
    view: true,
    add: true,
    update: true,
    group: "3. Clarity of Abstract",
    customClass: "quarter",
    tag: true,
  },
  {
    type: "number",
    placeholder: "Min Value",
    name: "clarityMinValue",
    label: "Min Value",
    required: true,
    view: true,
    add: true,
    update: true,
    group: "3. Clarity of Abstract",
    customClass: "half",
  },
  {
    type: "number",
    placeholder: "Max Value",
    name: "clarityMaxValue",
    label: "Max Value",
    required: true,
    view: true,
    add: true,
    update: true,
    group: "3. Clarity of Abstract",
    customClass: "half",
  },
  {
    type: "text",
    placeholder: "Min Label",
    name: "clarityMinLabel",
    label: "Min Label",
    required: false,
    view: true,
    add: true,
    update: true,
    group: "3. Clarity of Abstract",
    customClass: "half",
  },
  {
    type: "text",
    placeholder: "Max Label",
    name: "clarityMaxLabel",
    label: "Max Label",
    required: false,
    view: true,
    add: true,
    update: true,
    group: "3. Clarity of Abstract",
    customClass: "half",
  },
  // Section: 4. Relevance to Conference
  {
    type: "text",
    placeholder: "Criterion Title",
    name: "relevanceTitle",
    validation: "",
    default: "",
    tag: true,
    label: "Criterion Title",
    required: true,
    view: true,
    add: true,
    update: true,
    group: "4. Relevance to Conference",
    customClass: "full",
  },
  {
    type: "textarea",
    placeholder: "Description (Instructions for Reviewers)",
    name: "relevanceDescription",
    label: "Description (Instructions for Reviewers)",
    required: false,
    view: true,
    add: true,
    update: true,
    group: "4. Relevance to Conference",
    customClass: "full",
  },
  {
    type: "select",
    name: "relevanceResponseType",
    label: "Scale Rating",
    required: true,
    view: true,
    add: true,
    update: true,
    apiType: "JSON",
    selectApi: [
      { id: "1-5", value: "Scale Rating (1-5)" },
      { id: "1-10", value: "Scale Rating (1-10)" },
    ],
    customClass: "half",
    group: "4. Relevance to Conference",
  },
  {
    type: "number",
    placeholder: "Weight (%)",
    name: "relevanceWeight",
    label: "Weight (%)",
    required: true,
    view: true,
    add: true,
    update: true,
    group: "4. Relevance to Conference",
    customClass: "quarter",
    tag: true,
  },
  {
    type: "checkbox",
    name: "relevanceRequired",
    label: "Required (reviewers must answer)",
    default: false,
    required: false,
    view: true,
    add: true,
    update: true,
    group: "4. Relevance to Conference",
    customClass: "quarter",
    tag: true,
  },
  {
    type: "number",
    placeholder: "Min Value",
    name: "relevanceMinValue",
    label: "Min Value",
    required: true,
    view: true,
    add: true,
    update: true,
    group: "4. Relevance to Conference",
    customClass: "half",
  },
  {
    type: "number",
    placeholder: "Max Value",
    name: "relevanceMaxValue",
    label: "Max Value",
    required: true,
    view: true,
    add: true,
    update: true,
    group: "4. Relevance to Conference",
    customClass: "half",
  },
  {
    type: "text",
    placeholder: "Min Label",
    name: "relevanceMinLabel",
    label: "Min Label",
    required: false,
    view: true,
    add: true,
    update: true,
    group: "4. Relevance to Conference",
    customClass: "half",
  },
  {
    type: "text",
    placeholder: "Max Label",
    name: "relevanceMaxLabel",
    label: "Max Label",
    required: false,
    view: true,
    add: true,
    update: true,
    group: "4. Relevance to Conference",
    customClass: "half",
  },
  // Section: 5. Overall Comments
  {
    type: "text",
    placeholder: "Criterion Title",
    name: "overallTitle",
    validation: "",
    default: "",
    tag: true,
    label: "Criterion Title",
    required: true,
    view: true,
    add: true,
    update: true,
    group: "5. Overall Comments",
    customClass: "full",
  },
  {
    type: "textarea",
    placeholder: "Description (Instructions for Reviewers)",
    name: "overallDescription",
    label: "Description (Instructions for Reviewers)",
    required: false,
    view: true,
    add: true,
    update: true,
    group: "5. Overall Comments",
    customClass: "full",
  },
  {
    type: "select",
    name: "overallResponseType",
    label: "Scale Rating",
    required: true,
    view: true,
    add: true,
    update: true,
    apiType: "JSON",
    selectApi: [
      { id: "1-5", value: "Scale Rating (1-5)" },
      { id: "1-10", value: "Scale Rating (1-10)" },
    ],
    customClass: "half",
    group: "5. Overall Comments",
  },
  {
    type: "number",
    placeholder: "Weight (%)",
    name: "overallWeight",
    label: "Weight (%)",
    required: true,
    view: true,
    add: true,
    update: true,
    group: "5. Overall Comments",
    customClass: "quarter",
    tag: true,
  },
  {
    type: "checkbox",
    name: "overallRequired",
    label: "Required (reviewers must answer)",
    default: false,
    required: false,
    view: true,
    add: true,
    update: true,
    group: "5. Overall Comments",
    customClass: "quarter",
    tag: true,
  },
  {
    type: "number",
    placeholder: "Min Value",
    name: "overallMinValue",
    label: "Min Value",
    required: true,
    view: true,
    add: true,
    update: true,
    group: "5. Overall Comments",
    customClass: "half",
  },
  {
    type: "number",
    placeholder: "Max Value",
    name: "overallMaxValue",
    label: "Max Value",
    required: true,
    view: true,
    add: true,
    update: true,
    group: "5. Overall Comments",
    customClass: "half",
  },
  {
    type: "text",
    placeholder: "Min Label",
    name: "overallMinLabel",
    label: "Min Label",
    required: false,
    view: true,
    add: true,
    update: true,
    group: "5. Overall Comments",
    customClass: "half",
    },
  {
    type: "text",
    placeholder: "Max Label",
    name: "overallMaxLabel",
    label: "Max Label",
    required: false,
    view: true,
    add: true,
    update: true,
    group: "5. Overall Comments",
    customClass: "half",
    },
];
