export const leaderboardAttributes = [
  {
    type: "text",
    placeholder: "Rank",
    name: "rank",
    label: "Rank",
    validation: "",
    tag: true,
    required: true,
    view: true,
    add: true,
    update: true,
  },
  {
    type: "text",
    placeholder: "Participant",
    name: "userName",
    validation: "",
    default: "",
    label: "Participant",
    tag: true,
    required: true,
    view: true,
    add: true,
    update: true,
  },
  {
    type: "text",
    placeholder: "Email",
    name: "email",
    validation: "",
    label: "Email",
    tag: true,
    required: true,
    view: true,
    add: true,
    update: true,
    filter: true,
  },
  {
    type: "text",
    placeholder: "Total Points",
    name: "totalPoints",
    label: "Total Points",
    validation: "",
    tag: true,
    required: true,
    view: true,
    add: true,
    update: true,
  },
];
