export const manageChallengesAttributes = [
  {
    type: "text",
    placeholder: "Challenge Name",
    name: "title",
    validation: "",
    default: "",
    label: "Challenge Name",
    tag: true,
    required: true,
    view: true,
    add: true,
    update: true,
  },
  // {
  //   type: "text",
  //   placeholder: "Type",
  //   name: "action",
  //   validation: "",
  //   default: "App Action",
  //   label: "Type",
  //   tag: true,
  //   required: true,
  //   view: true,
  //   add: true,
  //   update: true,
  //   filter: true,
  // },
  {
    type: "text",
    placeholder: "Points",
    name: "points",
    validation: "",
    default: "",
    label: "Points",
    tag: true,
    required: true,
    view: true,
    add: true,
    update: true,
    filter: true,
  },

  {
    type: "select",
    placeholder: "Frequency",
    name: "type",
    default: "Single",
    label: "Frequency",
    apiType: "CSV",
    selectApi: "Single,Recurring",
    tag: true,
    required: true,
    view: true,
    add: true,
    update: true,
    filter: true,
  },
  {
    type: "toggle",
    placeholder: "Status",
    name: "status",
    default: true,
    label: "",
    showLabel: false,
    validation: "",
    tag: true,
    required: true,
    view: true,
    add: true,
    update: true,
    inlineAction: true,
  },
];