export const positionRewardsAttributes = [
  {
    type: "text",
    placeholder: "Prize Name",
    name: "prizeName",
    label: "Prize Name",
    validation: "required",
    default: "",
    add: true,
    update: true,
    view: true,
    customClass: "full",
    required: true,
    highlight: true, // Note: Highlight the prize name in card view
    icon: "trophy", // Note: Add trophy icon for visual appeal
  },
  {
    type: "text",
    placeholder: "Prize Value",
    name: "prizeValue",
    label: "Prize Value",
    validation: "required",
    tag: true,
    view: true,
    add: true,
    update: true,
    customClass: "full",
    required: true,
    // icon: "Pricing", // Note: Add dollar icon for prize value
  },
  // {
  //   type: "number",
  //   placeholder: "Position",
  //   name: "position",
  //   label: "Position",
  //   validation: "required|min:1",
  //   tag: true,
  //   view: true,
  //   add: true,
  //   update: true,
  //   customClass: "full",
  //   required: true,
  //   icon: "medal", // Note: Add medal icon for position
  //   min: 1,
  // },
  {
    type: "textarea",
    placeholder: "Prize Description",
    name: "prizeDescription",
    label: "Description",
    validation: "",
    tag: true, // Note: Don't show as tag in card view
    view: true,
    add: true,
    update: true,
    customClass: "full",
    rows: 3,
    footnote: "Optional description of the prize",
  },
];

export const milestoneRewardsAttributes = [
  
   
      {
        type: "number",
        placeholder: "Points Required",
        name: "pointsRequired",
        validation: "",
        default: "",
        label: "Points Required",
        add: true,
        view: true,
        update: true,
        tag: true,
        customClass: "full",
      },
      {
        type: "text",
        placeholder: "Reward Name",
        name: "rewardName",
        validation: "",
        default: "",
        label: "Reward Name",
        add: true,
        view: true,
        update: true,
        tag: true,
        customClass: "full",
      },
      {
        type: "textarea",
        placeholder: "Reward Description",
        name: "description",
        label: "Description",
        validation: "",
        add: true,
        view: true,
        update: true,
        customClass: "full",
      },
      {
        type: "text",
        placeholder: "Coupon Code",
        name: "coupon",
        label: "Coupon Code",
        validation: "",
        tag: true,
        add: true,
        view: true,
        update: true,
        customClass: "full",
      },
      {
        type: "text",
        placeholder: "Reward Value",
        name: "rewardValue",
        label: "Reward Value",
        validation: "",
        tag: true,
        add: true,
        view: true,
        update: true,
        customClass: "full",
      },
      {
        type: "toggle",
        placeholder: "Send Notification",
        name: "notify",
        label: "Send notification when milestone is reached",
        validation: "",
        default: false,
        tag: true,
        add: true,
        view: true,
        update: true,
        customClass: "full",
      },
];
