export const requestAppAttributes = [
  {
    type: "text",
    placeholder: "Name",
    name: "name",
    validation: "",
    default: "",
    label: "Name",
    required: true,
    tag: true,
    view: true,
    add: true,
    update: true,
    image: { type: "image", field: "image", collection: "" },
  },
  {
    type: "textarea",
    placeholder: "Description",
    name: "description",
    validation: "",
    default: "",
    label: "Description",
    required: false,
    tag: true,
    view: true,
    add: true,
    update: true,
  },
  {
    type: "image",
    placeholder: "Image",
    name: "image",
    validation: "",
    default: "",
    label: "Image",
    icon: "image",
    required: false,
    tag: false,
    view: true,
    add: true,
    update: true,
  },
];
