export const appVersionAttributes = [
  {
    type: "text",
    placeholder: "App",
    name: "app",
    validation: "",
    default: "",
    label: "App",
    required: false,
    tag: false,
    view: false,
    add: false,
    update: false,
  },
  {
    type: "text",
    placeholder: "Android Version",
    name: "androidVersion",
    validation: "",
    default: "",
    label: "Android Version",
    required: false,
    tag: true,
    view: true,
    add: true,
    update: true,
  },
  {
    type: "text",
    placeholder: "iOS Version",
    name: "iosVersion",
    validation: "",
    default: "",
    label: "iOS Version",
    required: false,
    tag: true,
    view: true,
    add: true,
    update: true,
  },
  {
    type: "toggle",
    placeholder: "Force Update",
    name: "forceUpdate",
    validation: "",
    default: false,
    label: "Force Update",
    required: false,
    tag: true,
    view: true,
    add: true,
    update: true,
  },
  {
    type: "text",
    placeholder: "Android Url",
    name: "androidUrl",
    validation: "",
    default: "",
    label: "Android Url",
    required: false,
    tag: true,
    view: true,
    add: true,
    update: true,
  },
  {
    type: "text",
    placeholder: "iOS Url",
    name: "iosUrl",
    validation: "",
    default: "",
    label: "iOS Url",
    required: false,
    tag: true,
    view: true,
    add: true,
    update: true,
  },
  {
    type: "textarea",
    placeholder: "Release Notes",
    name: "releaseNotes",
    validation: "",
    default: "",
    label: "Release Notes",
    required: false,
    tag: false,
    view: true,
    add: true,
    update: true,
  },
];
