export const checkoutSettingsAttributes = [
  {
    type: "titleswitch",
    title: "Checkout Settings",
    description: "Customize your checkout experience and configure how customers complete their purchases",
    group: "Header Appearance",
    add: true,
    update: true,
  },
  {
    type: "titleswitch",
    title: "Header Appearance",
    description: "Choose between a solid color or custom image for your checkout header",
    group: "Header Appearance",
    subGroup: "header-appearance",
    icon: "color-palette",
    add: true,
    update: true,
  },
  {
    type: "line",
    group: "Header Appearance",
    subGroup: "header-appearance",
    add: true,
    update: true,
  },
  {
    type: "select",
    placeholder: "Header Appearance",
    name: "headerAppearance",
    validation: "",
    editable: true,
    default: "solidColor",
    label: "Header Appearance",
    group: "Header Appearance",
    subGroup: "header-appearance",
    required: true,
    customClass: "half",
    filter: false,
    tag: true,
    view: true,
    add: true,
    update: true,
    apiType: "JSON",
    selectType: "card",
    selectApi: [
      { value: "Use solid color", id: "solidColor", description: "Specific sessions" },
      { value: "Use custom image", id: "customImage", description: "One or more stages" },
    ],
  },
  {
    type: "color",
    placeholder: "Header Background Color",
    name: "bgColor",
    validation: "",
    default: "#6366f1",
    label: "Header Background Color",
    group: "Header Appearance",
    subGroup: "header-appearance",
    condition: {
      item: "headerAppearance",
      if: "solidColor",
      then: "enabled",
      else: "disabled",
    },
    tag: true,
    required: false,
    view: true,
    add: true,
    update: true,
    customClass: "half",
  },
  {
    type: "image",
    placeholder: "Upload Header Image",
    name: "headerImage",
    validation: "",
    default: "#6366f1",
    label: "Upload Header Image",
    group: "Header Appearance",
    subGroup: "header-appearance",
    condition: {
      item: "headerAppearance",
      if: "customImage",
      then: "enabled",
      else: "disabled",
    },
    tag: true,
    required: false,
    view: true,
    add: true,
    update: true,
    footnote: "Recommended size: 1200*300px for best results",
  },
  {
    type: "titleswitch",
    title: "Ticket & Pricing Options",
    description: "Control how tickets are displayed and enable discount features",
    group: "Header Appearance",
    subGroup: "ticket-pricing",
    icon: "ticket",
    add: true,
    update: true,
  },
  {
    type: "line",
    group: "Header Appearance",
    subGroup: "ticket-pricing",
    add: true,
    update: true,
  },
  {
    type: "toggle",
    placeholder: "Group tickets by type",
    name: "groupTickets",
    label: "Group tickets by type",
    subLabel: "If applicable",
    default: true,
    required: false,
    view: true,
    add: true,
    update: true,
    tag: true,
    group: "Header Appearance",
    subGroup: "ticket-pricing",
    footnote: "Organize similar tickets together for easier selection",
  },
  {
    type: "toggle",
    placeholder: "Enable coupon codes",
    name: "enableCoupons",
    label: "Enable coupon codes",
    default: true,
    required: false,
    view: true,
    add: true,
    update: true,
    tag: true,
    group: "Header Appearance",
    subGroup: "ticket-pricing",
    footnote: "Allow customers to apply promotional or discount codes at checkout",
  },
  {
    type: "titleswitch",
    title: "Attendee Information",
    description: "Manage how attendee data is collected during checkout",
    group: "Header Appearance",
    subGroup: "attendee-info",
    icon: "participants",
    add: true,
    update: true,
  },
  {
    type: "line",
    group: "Header Appearance",
    subGroup: "attendee-info",
    add: true,
    update: true,
  },
  {
    type: "toggle",
    placeholder: "Collect individual attendee details",
    name: "collectAttendee",
    label: "Collect individual attendee details",
    default: true,
    required: false,
    view: true,
    add: true,
    update: true,
    tag: true,
    group: "Header Appearance",
    subGroup: "attendee-info",
    footnote: "Display information for each ticket holder",
  },
  {
    type: "toggle",
    placeholder: "Limit to one ticket per customer",
    name: "limitOne",
    label: "Limit to one ticket per customer",
    default: true,
    required: false,
    view: true,
    add: true,
    update: true,
    tag: true,
    group: "Header Appearance",
    subGroup: "attendee-info",
    footnote: "Restrict each customer to purchasing only one ticket (useful for exclusive events)",
  },
  {
    type: "titleswitch",
    title: "Post-Purchase Notifications",
    description: "Choose how customers receive their tickets and confirmations",
    group: "Header Appearance",
    subGroup: "post-purchase",
    icon: "message",
    add: true,
    update: true,
  },
  {
    type: "line",
    group: "Header Appearance",
    subGroup: "post-purchase",
    add: true,
    update: true,
  },
  {
    type: "toggle",
    placeholder: "Send invoice",
    name: "sendInvoice",
    label: "Send invoice",
    default: true,
    required: false,
    view: true,
    add: true,
    update: true,
    tag: true,
    group: "Header Appearance",
    subGroup: "post-purchase",
    footnote: "Restrict each customer to purchasing only one ticket (useful for exclusive events)",
  },
  {
    type: "toggle",
    placeholder: "Send email confirmation",
    name: "sendEmailConfirmation",
    label: "Send email confirmation",
    default: true,
    required: false,
    view: true,
    add: true,
    update: true,
    tag: true,
    group: "Header Appearance",
    subGroup: "post-purchase",
    footnote: "Restrict each customer to purchasing only one ticket (useful for exclusive events)",
  },
  {
    type: "text",
    placeholder: "Email Subject",
    name: "emailSubject",
    validation: "",
    default: "",
    tag: true,
    label: "Email Subject",
    condition: {
      item: "sendEmailConfirmation",
      if: true,
      then: "enabled",
      else: "disabled",
    },
    group: "Header Appearance",
    subGroup: "post-purchase",
    required: true,
    view: true,
    add: true,
    update: true,
  },
  {
    type: "htmleditor",
    placeholder: "Email Template",
    name: "emailMessage",
    validation: "",
    default: "",
    tag: true,
    label: "Email Template",
    condition: {
      item: "sendEmailConfirmation",
      if: true,
      then: "enabled",
      else: "disabled",
    },
    group: "Header Appearance",
    subGroup: "post-purchase",
    required: true,
    view: true,
    add: true,
    update: true,
  },
  {
    type: "toggle",
    placeholder: "Send WhatsApp notification",
    name: "sendWhatsappNotification",
    label: "Send WhatsApp notification",
    default: true,
    required: false,
    view: true,
    add: true,
    update: true,
    tag: true,
    group: "Header Appearance",
    subGroup: "post-purchase",
    footnote: "Restrict each customer to purchasing only one ticket (useful for exclusive events)",
  },
  {
    type: "toggle",
    placeholder: "Enable Tax",
    name: "enableTax",
    validation: "",
    default: "",
    group: "Header Appearance",
    subGroup: "post-purchase",
    label: "Enable Tax",
    tag: false,
    required: false,
    view: true,
    add: true,
    update: true,
  },
  {
    type: "text",
    placeholder: "Tax Percentage",
    name: "taxPercentage",
    validation: "",
    condition: {
      item: "enableTax",
      if: true,
      then: "enabled",
      else: "disabled",
    },
    default: true,
    tag: false,
    group: "Header Appearance",
    subGroup: "post-purchase",
    label: "Tax Percentage",
    required: false,
    view: true,
    add: true,
    update: true,
  },
];
