import React from "react";
import { COMPARE_TYPES } from "../../../core/functions/conditions";
import moment from "moment";
import { GetIcon } from "../../../../icons";
import QRCode from "react-qr-code";
import ReactDOM from "react-dom/client";
import EventChat from "../eventChat";

export const configureAppAttributes = [
  {
    type: "color",
    placeholder: "Theme Color",
    name: "themeColor",
    validation: "",
    default: "",
    label: "Theme Colour",
    // sublabel: "Optional",
    required: false,
    view: true,
    add: true,
    group: "Branding & Appearance",
    update: true,
    customClass: "half",
  },
  {
    type: "checkbox",
    placeholder: "Use Default",
    name: "themeColor",
    validation: "",
    default: "#6366f1",
    label: "Use Default",
    required: false,
    view: true,
    add: true,
    group: "Branding & Appearance",
    update: true,
    customClass: "quarter",
  },
  {
    type: "image",
    placeholder: "Main Banner",
    name: "mainBanner",
    validation: "",
    default: "",
    tag: true,
    label: "Main Banner",
    required: true,
    view: true,
    add: true,
    group: "Branding & Appearance",
    update: true,
  },
  {
    type: "checkbox",
    placeholder: "Use Default",
    name: "mainBanner",
    validation: "",
    default: false,
    label: "Use Default",
    required: false,
    view: true,
    add: true,
    group: "Branding & Appearance",
    update: true,
    customClass: "full",
  },
  {
    type: "image",
    placeholder: "Additional Banner",
    name: "additionalBanner",
    validation: "",
    default: "",
    tag: true,
    label: "Additional Banners",
    required: true,
    view: true,
    add: true,
    group: "Branding & Appearance",
    update: true,
  },
 
  {
    type: "toggle",
    placeholder: "Enable Attendee Chat",
    name: "enableAttendeeChat",
    validation: "",
    default: false,
    label: "Enable Attendee Chat",
    tag: true,
    required: false,
    view: true,
    add: true,
    update: true,
    group: "Attendee Chat",
  },

  {
    type: "textarea",
    placeholder: "e.g., 'Welcome! Please be respectful and use this space for networking.'",
    name: "attendeeChatAdditionalContext",
    validation: "",
    default: "",
    label: "Additional Context",
    required: false,
    view: true,
    add: true,
    update: true,
    group: "Attendee Chat",
    footnote:
      "This text will be shown as a welcome message or pinned post in the main chat channel.",
    condition: {
      item: "enableAttendeeChat",
      if: true,
      then: "enabled",
      else: "disabled",
    },
    customClass: "full",
    icon: "text",
  },
  {
    type: "element",
    name: "attendeeChatInline",
    label: "Attendee Chat",
    group: "Attendee Chat",
    add: true,
    update: true,
    view: true,
    customClass: "full",
    condition: {
      item: "enableAttendeeChat",
      if: true,
      then: "enabled",
      else: "disabled",
    },
    element: (props) => (
      <EventChat openData={{ data: { _id: props.referenceId } }} />
    ),
  },
  

  // Enable Modules
  {
    type: "multiSelect",
    placeholder: "Select Modules",
    name: "enableModules",
    validation: "",
    default: ["Sessions", "Speakers", "Networking","Exhibitors"],
    label: "Enable Modules",
    group: "Enable Modules",
    required: false,
    view: true,
    add: true,
    update: true,
    selectType: "card",
    apiType: "CSV",
    selectApi: "Sessions,Speakers,Networking,Exhibitors",
    customClass: "half",
  },

  // {
  //   type: "title",
  //   title: "Availability and Capacity",
  //   name: "availabilityAndCapacity",
  //   icon: "configuration",
  //   group: "Availability",
  //   add: true,
  //   update: true,
  // },
  {
    type: "text",
    placeholder: "eg: Welcome Survey",
    name: "nameHomePage",
    validation: "",
    tag: true,
    label: "Name",
    group: "Enable Forms In Home Page",
    // default: "Vertical",
    required: false,
    view: true,
    filter: true,
    add: true,
    update: true,
    icon: "form-builder",
  },
  {
    type: "select",
    placeholder: "",
    name: "attachCustomForm",
    validation: "",
    default: "Select form you have Created",
    label: "Attach Custom Form",
    group: "Enable Forms In Home Page",
    tag: false,
    required: false,
    view: true,
    add: true,
    update: true,
    apiType: "CSV",
    selectApi: "Select form you have Created,Post-Event Feedback,Lead Capture Form",
  },
  {
    type: "textarea",
    placeholder: "eg: Welcome Survey",
    name: "descriptionHomePage",
    validation: "",
    tag: false,
    label: "Description",
    group: "Enable Forms In Home Page",
    // default: "Vertical",
    required: false,
    view: true,
    filter: true,
    add: true,
    update: true,
    icon: "text",
  },
  {
    type: "select",
    placeholder: "Control what users can see before logging in",
    name: "signInRequired",
    validation: "",
    default: "Sign In Required",
    label: "Control what users can see before logging in",
    group: "Access",
    tag: false,
    view: true,
    required: true,
    add: true,  
    update: true,
    icon: "user",
    selectApi: [
      { id: "Sign In Required", value: "Sign In Required", description: "Attendees must log in to see any event content." },
      { id: "Not Required (Public)", value: "Not Required (Public)", description: "Allow anyone with the app to see basic info like speakers and session list without signing in." },
    ],
    apiType: "JSON",
    selectType: "radio",
    customClass: "full",
  },
];
