export const updatesAttributes = [
  {
    type: "text",
    placeholder: "Title",
    name: "title",
    label: "Title",
    required: true,
    tag: true,
    view: true,
    add: true,
    update: true,
    image: { type: "image", field: "image", collection: "" },
  },
  {
    type: "textarea",
    placeholder: "Description",
    name: "description",
    label: "Description",
    required: false,
    view: true,
    tag: true,
    add: true,
    update: true,
  },
  {
    type: "image",
    placeholder: "Image",
    name: "image",
    label: "Image",
    required: false,
    view: true,
    add: true,
    update: true,
  },
];
